//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDentalClinic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations.Schema;


    public partial class BENHNHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BENHNHAN()
        {
            this.PHIEUKHAMs = new HashSet<PHIEUKHAM>();
        }
        [Key, Column(Order = 1)]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        [Display(Name = "Mã Bệnh Nhân")]
        public int MaBenhNhan { get; set; }
        [Required]
        [Display(Name = "Họ Tên")]
        public string HoTen { get; set; }
        [Required]
        [Display(Name = "Giới Tính")]
        public string GioiTinh { get; set; }
        [Required]
        [Display(Name = "Năm Sinh")]
        public DateTime NamSinh { get; set; }
        [Required]
        [Display(Name = "Số Điện Thoại")]
        public string SoDienThoai { get; set; }
        [Required]
        [Display(Name = "Địa Chỉ")]
        public string DiaChi { get; set; }
        [Required]
        [Display(Name ="Mật khẩu")]
        public string MatKhau { get; set; }

        [NotMapped]
        [Required]
        [Display(Name = "Xác nhận mật khẩu")]
        [System.ComponentModel.DataAnnotations.Compare("MatKhau")]
        public string XacNhanMatKhau { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUKHAM> PHIEUKHAMs { get; set; }
    }
}
