//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDentalClinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUKHAMBENH
    {
        public string MaChiTietPhieuKham { get; set; }
        public string MaHoaDon { get; set; }
        public string MaPhieuKham { get; set; }
        public string MaDichVu { get; set; }
        public string TenDichVu { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual HOADONTHANHTOAN HOADONTHANHTOAN { get; set; }
        public virtual PHIEUKHAMBENH PHIEUKHAMBENH { get; set; }
    }
}
