//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDentalClinic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CHITIETPHIEUKHAM
    {
        [Key]
        public int MaChiTietPhieuKham { get; set; }
        
        public Nullable<int> MaPhieuKham { get; set; }
        [Display(Name ="Dịch Vụ")]
        public Nullable<int> MaDichVu { get; set; }
        [Display(Name ="Số Lượng")]
        public Nullable<int> SoLuong { get; set; }
        [Display(Name ="Ghi Chú")]
        public string GhiChu { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual PHIEUKHAM PHIEUKHAM { get; set; }
    }
}
