//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDentalClinic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class HOADON
    {
        [Key]

        [Display(Name = "Mã Hóa Đơn")]
        public int MaHoaDon { get; set; }
        [Display(Name = "Ngày Lập")]
        [DataType(DataType.Date)]

       /* [Required(ErrorMessage = "Vui lòng chọn ngày")]*/
        public Nullable<System.DateTime> NgayLap { get; set; }
      /*  [Required(ErrorMessage = "Vui lòng nhập mã phiếu khám")]*/
        [Display(Name = "Mã Phiếu Khám")]
        public Nullable<int> MaPhieuKham { get; set; }
        [Display(Name = "Tổng Tiền")]
   /*     [Required(ErrorMessage = "Vui lòng nhập tổng tiền")]*/
        public int TongTien { get; set; }
    
        public virtual PHIEUKHAM PHIEUKHAM { get; set; }
    }
}
