//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDentalClinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHHEN
    {
        public int MaLichHen { get; set; }
        public string HoTen { get; set; }
        public string SoDienThoai { get; set; }
        public Nullable<System.DateTime> NgayHen { get; set; }
        public string GioHen { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
