//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDentalClinic.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebPhongKhamNhaKhoaEntities : DbContext
    {
        public WebPhongKhamNhaKhoaEntities()
            : base("name=WebPhongKhamNhaKhoaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BENHNHAN> BENHNHANs { get; set; }
        public virtual DbSet<CHITIETLICHHEN> CHITIETLICHHENs { get; set; }
        public virtual DbSet<CHITIETPHIEUKHAMBENH> CHITIETPHIEUKHAMBENHs { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<DICHVU> DICHVUs { get; set; }
        public virtual DbSet<HOADONTHANHTOAN> HOADONTHANHTOANs { get; set; }
        public virtual DbSet<LICHHEN> LICHHENs { get; set; }
        public virtual DbSet<LOAIDICHVU> LOAIDICHVUs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHIEUKHAMBENH> PHIEUKHAMBENHs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAIKHOANBENHNHAN> TAIKHOANBENHNHANs { get; set; }
        public virtual DbSet<TAIKHOANNHANVIEN> TAIKHOANNHANVIENs { get; set; }
    }
}
