//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDentalClinic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.CHITIETLICHHENs = new HashSet<CHITIETLICHHEN>();
            this.PHIEUKHAMBENHs = new HashSet<PHIEUKHAMBENH>();
        }
        [Display(Name = "Mã Nhân Viên")]
        public string MaNhanVien { get; set; }
        [Display(Name = "Họ Tên")]
        public string HoTen { get; set; }
        [Display(Name = "Giới Tính")]
        public string GioiTinh { get; set; }
        [Display(Name = "Năm Sinh")]
        public Nullable<System.DateTime> NamSinh { get; set; }
        [Display(Name = "Số Điện Thoại")]
        public Nullable<int> SoDienThoai { get; set; }
        [Display(Name = "Địa Chỉ")]
        public string DiaChi { get; set; }
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Display(Name = "Chức Vụ")]
        public string MaChucVu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETLICHHEN> CHITIETLICHHENs { get; set; }
        public virtual CHUCVU CHUCVU { get; set; }
        public virtual TAIKHOANNHANVIEN TAIKHOANNHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUKHAMBENH> PHIEUKHAMBENHs { get; set; }
    }
}
