//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDentalClinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUKHAMBENH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUKHAMBENH()
        {
            this.CHITIETPHIEUKHAMBENHs = new HashSet<CHITIETPHIEUKHAMBENH>();
        }
    
        public string MaPhieuKham { get; set; }
        public string MaNhanVien { get; set; }
        public string MaBenhNhan { get; set; }
        public Nullable<System.DateTime> NgayKham { get; set; }
        public Nullable<System.TimeSpan> GioKham { get; set; }
        public Nullable<System.DateTime> NgayTaiKham { get; set; }
        public string MoTaTrieuChung { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    
        public virtual BENHNHAN BENHNHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUKHAMBENH> CHITIETPHIEUKHAMBENHs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
