//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDentalClinic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TAIKHOANNHANVIEN
    {
        [Key, Column(Order = 1)]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        [Display(Name = "Mã Bệnh Nhân")]
        public int MaNhanVien { get; set; }
        [Display(Name = "Tên Tài Khoản")]
        public string TenTaiKhoan { get; set; }
        [Display(Name = "Mật Khẩu")]

        public string MatKhau { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
