//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDentalClinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOANBENHNHAN
    {
        public int MaBenhNhan { get; set; }
        public string TenTaiKhoan { get; set; }
        public string MatKhau { get; set; }
    
        public virtual BENHNHAN BENHNHAN { get; set; }
    }
}
