//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDentalClinic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TAIKHOANBENHNHAN : BENHNHAN
    {
        
        [Display(Name = "Mã Bệnh Nhân")]
        public int MaBenhNhan { get; set; }
        /*[Required]*/
        [Display(Name = "Tên Tài Khoản")]
        public string TenTaiKhoan { get; set; }
        [Required]
        [Display(Name = "Mật Khẩu")]
        public string MatKhau { get; set; }

        [NotMapped]
        [Required]
        [System.ComponentModel.DataAnnotations.Compare("MatKhau")]
        [Display(Name = "Xác Nhận Mật Khẩu")]
        public string XacNhanMatKhau { get; set; }

        public virtual BENHNHAN BENHNHAN { get; set; }
    }
}
