//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDentalClinic.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    public partial class TAIKHOANBENHNHAN
    {
        [Required]
        [Display (Name = "ID tài khoản")]
        public string MaBenhNhan { get; set; }
        [Required]
        [Display(Name = "Tên tài khoản")]
        public string TenTaiKhoan { get; set; }
        [Required]
        [Display(Name = "Mật khẩu")]
        public string MatKhau { get; set; }

        [NotMapped]
        [Required]
        [Display(Name = "Xác nhận mật khẩu")]
        [System.ComponentModel.DataAnnotations.Compare("MatKhau")]
        public string XacNhanMatKhau { get; set; }

        public virtual BENHNHAN BENHNHAN { get; set; }
    }
}
