//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDentalClinic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TAIKHOANNHANVIEN
    {
        [Display(Name = "Mã B?nh Nhân")]
        public string MaNhanVien { get; set; }
        [Display(Name = "Tên Tài Kho?n")]
        public Nullable<int> TenTaiKhoan { get; set; }
        [Display(Name = "M?t Kh?u")]
        public string MatKhau { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
